name: Approve Github Repository Specific Deployments
on:
  issues:
    types:
     - opened
     - edited
jobs:
  approve_env_deployments:
    if: contains(github.event.issue.labels.*.name, 'approve_env_deployments')
    name: Approve Github Repository Specific Deployments
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: develop
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/APPROVE-ENVIRONMENT-DEPLOYMENTS.yml
      - name: echo inputs
        shell: bash
        env: 
          REPOSITORY: ${{ steps.issue-parser.outputs.issueparser_reponame }}
          ENVIRONMENT: ${{ steps.issue-parser.outputs.issueparser_environment }}
          RUN_ID: ${{ steps.issue-parser.outputs.issueparser_run_id }}
          REPOSITORY_WORKFLOW_DISPATCH: ${{ inputs.reponame }}
          ENVIRONMENT_WORKFLOW_DISPATCH: ${{ inputs.environment }}
          RUN_ID_WORKFLOW_DISPATCH: ${{ inputs.run_id }}
        run: |
           if [[ "${{ github.event_name }}" == "issues" ]]; then
             echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
             echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
             echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
           else
             echo "REPOSITORY=$REPOSITORY_WORKFLOW_DISPATCH" >> $GITHUB_ENV
             echo "ENVIRONMENT=$ENVIRONMENT_WORKFLOW_DISPATCH" >> $GITHUB_ENV
             echo "RUN_ID_WORKFLOW_DISPATCH=$RUN_ID_WORKFLOW_DISPATCH" >> $GITHUB_ENV
           fi
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/susanto-dev/projects/4
          github-token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/github-script@v7
        if: github.event_name == 'issues'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ' 👋 Thanks for opening an issue. It will be addressed soon'
            })

